name: CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'

permissions:
  contents: read
  id-token: write

jobs:
  test:
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  deploy:
    name: Terraform Deploy
    needs: test
    uses: ./.github/workflows/terraform_deploy.yml
    secrets: inherit
