name: Terraform Tests

on:
  workflow_call:

permissions:
  contents: read
  id-token: write

jobs:
  terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: ./terraform

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Assume the deploy pipeline user role
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ secrets.AWS_REGION }}
          managed-session-policies: arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess

      - name: Get tfvars file
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          aws s3 cp s3://virtual-spider-zoo/terraform.tfvars .

      - name: Terraform Init
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: make tf_init

      - name: Terraform Validate
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: make tf_validate

      - name: Terraform Plan
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: make tf_plan
